apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geo
  labels:
    app: geo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geo
    spec:
      restartPolicy: Always
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
          "-instances=instant-matter-785:asia-east1:meepshop-test=tcp:5432",
          "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssql/certs
          - name: cloudsql
            mountPath: /cloudsql
      - name: geo
        image: asia.gcr.io/instant-matter-785/geo:0.0.1
        env:
        - name: POSTGRES_DSN
          value: "postgres://postgres:8cyt5fsbINl95Num@localhost:5432/geo?sslmode=disable"
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:

